from fpdf import FPDF
import datetime
import re


def strip_markdown(text: str) -> str:
    """Remove markdown symbols and replace Unicode chars with ASCII."""

    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'__(.*?)__',     r'\1', text)
    text = re.sub(r'\*(.*?)\*',     r'\1', text)
    text = re.sub(r'_(.*?)_',       r'\1', text)
    text = re.sub(r'`(.*?)`',       r'\1', text)
    text = re.sub(r'^#{1,6}\s*',    '',    text, flags=re.MULTILINE)
    text = re.sub(r'^[-=]{3,}$',    '',    text, flags=re.MULTILINE)
    text = re.sub(r'^\s*[-*]\s+',   '  - ', text, flags=re.MULTILINE)

    replacements = {
        '\u2022': '-',    # bullet •
        '\u2019': "'",    # right single quote '
        '\u2018': "'",    # left single quote '
        '\u201c': '"',    # left double quote "
        '\u201d': '"',    # right double quote "
        '\u2013': '-',    # en dash -
        '\u2014': '--',   # em dash --
        '\u2026': '...', # ellipsis ...
        '\u00a0': ' ',    # non-breaking space
        '\u2012': '-',    # figure dash
        '\u00b7': '-',    # middle dot
        '\u25cf': '-',    # filled circle
        '\u27a2': '>',    # arrow
        '\u2192': '->',   # right arrow
        '\u00e9': 'e',    # e with accent
        '\u00e8': 'e',
        '\u00ea': 'e',
        '\u00e0': 'a',
        '\u00e2': 'a',
    }
    for uc, asc in replacements.items():
        text = text.replace(uc, asc)

    # Catch-all: any remaining non-Latin-1 chars become ?
    text = text.encode('latin-1', 'replace').decode('latin-1')

    return text


class ResearchPDF(FPDF):

    def __init__(self, topic: str):
        super().__init__()
        self.topic = topic

    def header(self):
        # Purple accent bar
        self.set_fill_color(108, 99, 255)
        self.rect(0, 0, 210, 3, 'F')

        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(160, 160, 185)
        self.set_xy(10, 6)

        # Sanitize topic before using it in header
        topic_clean = strip_markdown(self.topic)
        topic_short = topic_clean[:60] + "..." if len(topic_clean) > 60 else topic_clean
        self.cell(0, 6, "Research Report: " + topic_short, 0, 1, 'L')

        self.set_draw_color(30, 30, 46)
        self.line(10, 14, 200, 14)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_draw_color(30, 30, 46)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(60, 60, 80)
        date_str = datetime.datetime.now().strftime("%B %d, %Y")
        # Use | instead of middle dot to avoid Unicode crash
        self.cell(0, 10, "Page " + str(self.page_no()) + " | Generated " + date_str + " | AI Research Agent", 0, 0, 'C')


def generate_pdf(topic: str, report: str, critiques: list = None) -> bytes:
    """
    Converts a research report into a formatted PDF.
    Returns the PDF as bytes for st.download_button.
    """

    pdf = ResearchPDF(topic=topic)
    pdf.set_margins(15, 20, 15)
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── COVER PAGE ──────────────────────────────────────
    pdf.add_page()

    pdf.set_fill_color(108, 99, 255)
    pdf.rect(0, 0, 210, 60, 'F')

    pdf.set_font('Helvetica', 'B', 11)
    pdf.set_text_color(200, 195, 255)
    pdf.set_xy(15, 20)
    pdf.cell(0, 8, 'RESEARCH REPORT', 0, 1, 'L')

    pdf.set_font('Helvetica', 'B', 22)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(15, 30)
    pdf.multi_cell(180, 10, strip_markdown(topic), 0, 'L')

    pdf.set_y(75)
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(100, 100, 120)
    date_str = datetime.datetime.now().strftime("%B %d, %Y at %H:%M")
    pdf.cell(0, 7, "Generated on " + date_str, 0, 1, 'L')
    pdf.cell(0, 7, "Generated by Autonomous AI Research Agent", 0, 1, 'L')
    pdf.cell(0, 7, "Powered by LangGraph - GPT-4o-mini - Tavily", 0, 1, 'L')

    if critiques:
        pdf.cell(0, 7, "Quality reviewed by critic agent - " + str(len(critiques)) + " revision round(s)", 0, 1, 'L')

    pdf.ln(10)
    pdf.set_draw_color(108, 99, 255)
    pdf.set_line_width(0.5)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(10)

    pdf.set_font('Helvetica', 'I', 10)
    pdf.set_text_color(120, 120, 140)
    pdf.multi_cell(
        0, 6,
        "This report was autonomously generated by an AI research agent that "
        "searched the live internet, read multiple articles, and synthesized "
        "findings into this structured document.",
        0, 'L'
    )

    # ── REPORT CONTENT PAGE ─────────────────────────────
    pdf.add_page()

    for line in report.split('\n'):
        stripped = line.strip()

        if not stripped:
            pdf.ln(3)
            continue

        if stripped.startswith('# '):
            pdf.set_font('Helvetica', 'B', 16)
            pdf.set_text_color(108, 99, 255)
            pdf.ln(4)
            pdf.multi_cell(0, 8, strip_markdown(stripped), 0, 'L')
            pdf.ln(2)

        elif stripped.startswith('## '):
            pdf.set_font('Helvetica', 'B', 13)
            pdf.set_text_color(80, 75, 180)
            pdf.ln(3)
            pdf.multi_cell(0, 7, strip_markdown(stripped), 0, 'L')
            pdf.set_draw_color(40, 40, 60)
            pdf.line(15, pdf.get_y(), 195, pdf.get_y())
            pdf.ln(3)

        elif stripped.startswith('### '):
            pdf.set_font('Helvetica', 'B', 11)
            pdf.set_text_color(100, 95, 200)
            pdf.ln(2)
            pdf.multi_cell(0, 6, strip_markdown(stripped), 0, 'L')
            pdf.ln(1)

        elif stripped.startswith(('- ', '* ', '• ')):
            pdf.set_font('Helvetica', '', 10)
            pdf.set_text_color(50, 50, 65)
            pdf.set_x(20)
            pdf.multi_cell(0, 5.5, '-  ' + strip_markdown(stripped[2:]), 0, 'L')

        elif re.match(r'^\d+\.', stripped):
            pdf.set_font('Helvetica', '', 10)
            pdf.set_text_color(50, 50, 65)
            pdf.set_x(20)
            pdf.multi_cell(0, 5.5, strip_markdown(stripped), 0, 'L')

        else:
            pdf.set_font('Helvetica', '', 10)
            pdf.set_text_color(50, 50, 65)
            pdf.set_x(15)
            pdf.multi_cell(0, 5.5, strip_markdown(stripped), 0, 'L')

    # ── CRITIC FEEDBACK PAGE ────────────────────────────
    if critiques:
        pdf.add_page()

        pdf.set_font('Helvetica', 'B', 16)
        pdf.set_text_color(108, 99, 255)
        pdf.cell(0, 10, 'AI Critic Feedback', 0, 1, 'L')
        pdf.set_draw_color(108, 99, 255)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(5)

        pdf.set_font('Helvetica', '', 10)
        pdf.set_text_color(100, 100, 120)
        pdf.multi_cell(
            0, 6,
            "The following feedback was generated by a separate critic AI agent "
            "that reviewed each draft for gaps, bias, and missing information. "
            "The researcher agent then revised the report based on this feedback.",
            0, 'L'
        )
        pdf.ln(6)

        for i, critique in enumerate(critiques, 1):
            pdf.set_font('Helvetica', 'B', 10)
            pdf.set_text_color(180, 175, 255)
            pdf.cell(0, 8, '  Critic Round ' + str(i), 0, 1, 'L')
            pdf.ln(2)

            pdf.set_font('Helvetica', '', 9)
            pdf.set_text_color(100, 100, 120)
            pdf.set_x(20)
            pdf.multi_cell(0, 5.5, strip_markdown(critique), 0, 'L')
            pdf.ln(5)

    return bytes(pdf.output())